baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "My New Hugo Site"

# https://gohugo.io/extras/menus/#section-menu-for-the-lazy-blogger
SectionPagesMenu = "main"
